### ISSUE TITLE
Package request: luajit

### ISSUE THREAD

**Issue by 2m4qhki3** [termux/unstable-packages#100]
The following commit removed luajit: https://github.com/termux/termux-packages/commit/154bc46225dd80d5f073dd40d99924f95057b759

Perhaps luajit could be added back as a separate package from lua? It's being maintained upstream and there is an updated version available (luajit 2.1 beta 3): https://github.com/luajit/luajit

**Comment by xeffyr** [comment]
Package is now available.

You can obtain it with these commands:
```
pkg install unstable-repo
pkg install luajit
```
