### ISSUE TITLE
package request: lastpass-cli

### ISSUE THREAD

**Issue by BlueDrink9** [termux/unstable-packages#101]
Command-line interface to password manager `lastpass`.

[Build instructions for termux given here](https://lydericblog.wordpress.com/2017/09/23/compile-lastpass-cli-lpass-for-termux)

**Comment by xeffyr** [comment]
Package is now available.

You can obtain it with these commands:
```
pkg install unstable-repo
pkg install lastpass-cli
```

**Comment by BlueDrink9** [comment]
Thank you! So stoked about this

**Comment by lyderic** [comment]
Many thanks for this invaluable package!

**Comment by pschmitt** [comment]
For people trying to get the `-c` flag (copy to clipboard) to work you can add the following script to your `$PATH` and name it `xsel`:

```bash
#!/usr/bin/env bash

if [[ -t 0 ]]
then
  termux-clipboard-get
else
  read text
  termux-clipboard-set "$text"
fi

# vim: set ft=bash et ts=2 sw=2 :
```
