### ISSUE TITLE
Package request: wren

### ISSUE THREAD

**Issue by aquaratixc** [termux/unstable-packages#102]
**Package description**
Wren is simple and fast concurrent based programming language

**Link to home page and sources**
1. Home page: http://wren.io/
2. Source code: git clone https://github.com/munificent/wren.git

**Additional information**
I've tried to compile wren on my device but I got error with libuv (it's dependency for wren)

**Comment by xeffyr** [comment]
Package is now available.

You can obtain it with these commands:
```
pkg install unstable-repo
pkg install wren
```
