### ISSUE TITLE
[Package Request] fetchmail

### ISSUE THREAD

**Issue by geometryof** [termux/unstable-packages#104]
**Package description**
full-featured, robust, well-documented remote-mail retrieval and forwarding utility

**Link to home page and sources**
1. Home page: http://www.fetchmail.info/
2. Source code: https://sourceforge.net/projects/fetchmail/files/branch_6.3/

**Comment by xeffyr** [comment]
Package is now available.

You can obtain it with these commands:
```
pkg install unstable-repo
pkg install fetchmail
```
