### ISSUE TITLE
package request: AtomVM

### ISSUE THREAD

**Issue by Serkan-devel** [termux/unstable-packages#105]
[AtomVM](https://github.com/bettio/AtomVM) is an embeded implementation of the ErlangVM. This is comparable to micropython but for Erlang/Elixir.

Might great to use it on the go, next to https://github.com/termux/termux-packages/issues/392

**Comment by xeffyr** [comment]
Package is now available.

You can obtain it with these commands:
```
pkg install unstable-repo
pkg install atomvm
```
