### ISSUE TITLE
Package Request:  wavemon 

### ISSUE THREAD

**Issue by zcattacz** [termux/unstable-packages#110]
It would be pretty awesome if we can use  wavemon to track wifi strength. 
https://github.com/uoaerg/wavemon

**Comment by xeffyr** [comment]
Package is now available.

You can obtain it with these commands:
```
pkg install unstable-repo
pkg install wavemon
```

**Comment by GetRektBoy724** [comment]
Is this package require su?

**Comment by xeffyr** [comment]
Yes, it requires root.

**Comment by GetRektBoy724** [comment]
How to get root on termux,can i use fakeroot?and how to use fakeroot?


SORRY,IM LITTLE BIT NEW ON TERMUX!!

**Comment by xeffyr** [comment]
> How to get root on termux

Root your device.

> can i use fakeroot?and how to use fakeroot?

No. Fakeroot doesn't give you any permissions.
Fakeroot is a package purely for developers.

From Debian Wiki:

> Gives a fake root environment , to remove the need to become root for a package build.
>
>fakeroot runs a command in an environment where it appears to have root privileges for file manipulation. This is useful for allowing users to create archives (tar, ar, .deb etc.) with files in them with root permissions/ownership. Without fakeroot one would have to have root privileges to create the constituent files of the archives with the correct permissions and ownership, and then pack them up, or one would have to construct the archives directly, without using the archiver
