### ISSUE TITLE
Package request: kubectl 

### ISSUE THREAD

**Issue by luisdavim** [termux/unstable-packages#115]
Hi, would it be possible to add a kubectl build to the repos?

**Comment by xeffyr** [comment]
Package is now available.

You can obtain it with these commands:
```
pkg install unstable-repo
pkg install kubectl
```

**Comment by jwenz723** [comment]
> Package is now available.
> 
> You can obtain it with these commands:
> 
> ```
> pkg install unstable-repo
> pkg install kubectl
> ```

I was able to successfully install kubectl with these commands, but when I execute the downloaded binary I get the following error:

```
$ kubectl get pods
error: "kubectl": executable's TLS segment is underaligned: alignment is 8, needs to be at least 64 for ARM64 Bionic
Aborted
```

I am running on a pixel 3 with Android 10.
Any ideas what causes this?

**Comment by xeffyr** [comment]
> Any ideas what causes this?

Built with Go 1.12.x.
