### ISSUE TITLE
package request: makepasswd(from debian), and APG

### ISSUE THREAD

**Issue by GIJack** [termux/unstable-packages#12]
makepasswd is a random password generator from debian - http://packages.qa.debian.org/m/makepasswd.html 

APG is another password generator, supports pronounceable passwords - http://www.adel.nursat.kz/apg/index.shtml

**Comment by xeffyr** [comment]
Package is now available.

You can obtain it with these commands:
```
pkg install unstable-repo
pkg install apg
```
