### ISSUE TITLE
Package request

### ISSUE THREAD

**Issue by GetRektBoy724** [termux/unstable-packages#123]
Please add exiftool for termux

**Comment by xeffyr** [comment]
Where its source URL or at least homepage ?

**Comment by GetRektBoy724** [comment]
Waait a second.......

Its https://www.sno.phy.queensu.ca/~phil/exiftool/index.html

**Comment by xeffyr** [comment]
Added in https://github.com/termux/unstable-packages/commit/61a94a07846de2ff0f8f6baeb369b6f23ce7d4a2.
