### ISSUE TITLE
Request for qemu-user-static

### ISSUE THREAD

**Issue by FTC55** [termux/unstable-packages#124]
**Package description**
The static version of qemu-user would enable users to create cross architecture chroots using proot, something that is very difficult with the dynamically linked version.

**Link to home page and sources**
1. Home page: https://www.qemu.org
2. Source code: https://git.qemu.org/git/qemu.git

**Additional information**
Have you compiled or tried to compile the package on device?
* If it didn't work then please provide the error you ran into
* If it did work then please share any patches that you had to apply

No, I haven't tried since i feel like it would fail considering there are already multiple patches used for building the dynamically linked version of the corresponding termux package.

**Comment by FTC55** [comment]
Thank you for your quick how-to. Though I'm currently doing this with debootstrap and i'm getting this error upon running second stage ```qemu: uncaught target signal 11 (Segmentation fault) - core dumped
Segmentation fault``` . It seems to be coming from /sbin/ldconfig

**Comment by xeffyr** [comment]
Because qemu is unstable.

**Comment by FTC55** [comment]
I think i got around that issue but I'm back at what lead me to make this request, which i apologize if i didn't explain correctly originally. I'm now using the command that is provided in the official guide for proot in the termux wiki, that is, ```proot -0 -r ./oldstable -b /dev/ -b /sys/ -b /proc/ -b /data/data/com.termux/files/home /usr/bin/env -i HOME=/root TERM="xterm-256color" PS1='[root@stable \W]$ ' PATH=/bin:/usr/bin:/sbin:/usr/sbin:/bin /bin/bash --login``` but slightly modified to include the -q argument and the oldstable version of debian as opposed as the one included in the guide. I switched to this one because the one you provided only works for me on that specific rootfs and when i try using it on a debian rootfs the shell prefix changes to $ but running ```uname -a``` reveals that we're still running on aarch64. Now with the new one I'm using though, (i suppose due to the chroot) qemu itself fails to link: ```proot -q qemu-x86_64 -0 -r ./oldstable -b /dev/ -b /sys/ -b /proc/ -b /data/data/com.termux/files/home /usr/bin/env -i HOME=/root TERM="xterm-256color" PS1='[root@stable \W]$ ' PATH=/bin:/usr/bin:/sbin:/usr/sbin:/bin /bin/bash --login
CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/bin/qemu-x86_64": library "liblog.so" not found```

**Comment by xeffyr** [comment]
I have added `-b /system:/system` and `-b /data:/data` to make sure that qemu is linked properly.

**Comment by SmartArray** [comment]
> Because qemu is unstable

That's definitely not the reason in this case.

I had a similar issue with ```debootstrap``` just yesterday, and I discovered that the directory ```/var/cache/ldconfig``` did not exist on the target.

Please ensure the directory exists, before you run ```debootstrap```

**Comment by FTC55** [comment]
@SmartArray debootstrap will fail regardless at --second-stage so i kind of gave up on debian. It has multiple issues with dpkg and getting packages to install is a nightmare

**Comment by xeffyr** [comment]
Closing as package is [added](https://bintray.com/xeffyr/unstable-packages-24/qemu-user-static) (no build.sh/patches available since it is manual build).
```
pkg install qemu-user-static
```
