### ISSUE TITLE
metasploit issue "cant link executable bigdecimal.so"

### ISSUE THREAD

**Issue by remo7777** [termux/unstable-packages#130]
device architecture is armv8l
`uname -m` armv8l

and
when i search bigdecimal.so 

`find $PREFIX/ -iname bigdecimal.so`
`/data/data/com.termux/files/usr/lib/ruby/2.6.0/aarch64-linux-android/bigdecimal.so`

**Comment by xeffyr** [comment]
Post output of `dpkg --print-architecture` and `file $PREFIX/bin/bash`.

`armv8l` is 32 bit (ARM) environment on 64 bit (aarch64) device, therefore all Termux packages should be 32bit / arm. Having `/data/data/com.termux/files/usr/lib/ruby/2.6.0/aarch64-linux-android/bigdecimal.so` is something really wrong.

**Comment by remo7777** [comment]
yes... 😝😝

**Comment by remo7777** [comment]
so i need to edit msfconsole like 

``#!/data/data/com.termux/files/usr/bin/sh

SCRIPT_NAME=$(basename "$0")
METASPLOIT_PATH="/data/data/com.termux/files/usr/opt/metasploit-framework"

case "$(uname -m)" in
        aarch64)
                export LD_PRELOAD="$LD_PRELOAD:/data/data/com.termux/files/usr/lib/ruby/2.6.0/aarch64-linux-android/bigdecimal.so"
                ;;
        arm*)
                export LD_PRELOAD="$LD_PRELOAD:/data/data/com.termux/files/usr/lib/ruby/2.6.0/aarch64-linux-android/bigdecimal.so"
                ;;``

am i right ??

**Comment by xeffyr** [comment]
Yes, in your case it seems should be
```
export LD_PRELOAD="$LD_PRELOAD:/data/data/com.termux/files/usr/lib/ruby/2.6.0/aarch64-linux-android/bigdecimal.so"
```
but it really strange that ruby assumes that `armv8l` equals `aarch64`. I need to check why that happens and if everything seems okay, I just make
```
aarch64|armv8l)
export LD_PRELOAD="$LD_PRELOAD:/data/data/com.termux/files/usr/lib/ruby/2.6.0/aarch64-linux-android/bigdecimal.so"
;;
```

**Comment by remo7777** [comment]
https://github.com/termux/unstable-packages/issues/130#issuecomment-537662526

wow nice...

**Comment by remo7777** [comment]
i have same issue with proot program but i will open issue another one
and thank you brother.
