### ISSUE TITLE
Vlang missing vlib

### ISSUE THREAD

**Issue by pollen5** [termux/unstable-packages#131]
I just tested vlang, it can't compile code without the vlib folder which holds the standard library packages
```
pollen@localhost ~/vstuff> cat main.v

fn main() {
  println('Hello, World!')
}
pollen@localhost ~/vstuff> v main.v
vlib not found. It should be next to the V executable.
Go to https://vlang.io to install V.
```

**Comment by xeffyr** [comment]
Where the `vlib` should be placed ? In directory with `v` executable ?
What I can see from its readme/makefile, it doesn't support normal packaging currently.

**Comment by pollen5** [comment]
Yes in the executable dir, the install instructions does use a symlink to make it available to path, so perhaps install v and vlib in $PREFIX/lib/v (use any dir appropriate this is just an example) and symlink the executable to $PREFIX/bin

**Comment by pollen5** [comment]
@xeffyr the update you released fixed the vlib missing problem, but care to explain why you used an exec wrapper instead of a symlink? 

Secondly there is now another linker error
```
pollen@localhost ~/vstuff> v main.v
/data/data/com.termux/files/usr/bin/arm-linux-androideabi-ld: /data/data/com.termux/files/usr/lib/libpthread.so: undefined reference to `android_get_application_target_sdk_version@LIBC_PLATFORM'
clang...
(Use `v -debug` to print the entire error message)

V error: C error. This should never happen. Please create a GitHub issue: https://github.com/vlang/v/issues/new/choose
pollen@localhost ~/vstuff>
```
i did open an issue on their repo but mentioning here just in case if you think it's related to termux.

**Comment by xeffyr** [comment]
> /data/data/com.termux/files/usr/bin/arm-linux-androideabi-ld: /data/data/com.termux/files/usr/lib/libpthread.so: undefined reference to `android_get_application_target_sdk_version@LIBC_PLATFORM'

I don't have such error. Your `main.v` works fine for me.

**Comment by xeffyr** [comment]
And try to `v -o prog main.v` because just `v main.v` doesn't generate executable for some reason.

**Comment by pollen5** [comment]
Fixed, had to update ndk-sysroot, yet another issue due to outdated packages :/ should pay more attention to updates.
