### ISSUE TITLE
Request for zeronet python3

### ISSUE THREAD

**Issue by japzone1** [termux/unstable-packages#134]
Can the zeronet package be updated to the new python3 version, or at least have a separate python3 package added? The python2 version is legacy software now and doesn't get new feature updates.

I've verified that the python3 version does run in Termux, though I had to go through dependency hell to get it to run, which is why it'd be nice to have an "official" package for average users that'd get frustrated by having to repeatedly debug missing dependencies.

**Comment by japzone1** [comment]
Derp, missed the rule about not posting requests here.

**Comment by xeffyr** [comment]
Yes, I agree that we need zeronet for python 3.
Zeronet for python 3 has different dependency list, so I need to deal with that before updated package version will be available.
