### ISSUE TITLE
Package request: fbless

### ISSUE THREAD

**Issue by ClockGen** [termux/unstable-packages#14]
An ncurses-based fictionbook2 reader written in python. Supports theming, hyphenation, autoscroll and some other features.
Depends on python2 and ncurses.
Works out of the box in termux (if shebang in main script is fixed).
https://github.com/ashinkarov/fbless

**Comment by xeffyr** [comment]
Package is now available.

You can obtain it with these commands:
```
pkg install unstable-repo
pkg install fbless
```
