### ISSUE TITLE
when run setoolkit have force exit.(without-root)

### ISSUE THREAD

**Issue by Beatgrim** [termux/unstable-packages#140]
![Screenshot_20191026-052424_Termux](https://user-images.githubusercontent.com/44520884/67608260-ffb89800-f776-11e9-81d8-610be9a31992.jpg)
How to fix this?

**Comment by Beatgrim** [comment]
Sorry i'm forgot to read status package

**Comment by xeffyr** [comment]
Error tells you that you didn't executed it as root.
