### ISSUE TITLE
Package request: e2fsprogs

### ISSUE THREAD

**Issue by pawamoy** [termux/unstable-packages#15]
https://github.com/tytso/e2fsprogs

I am especially interested in the commands `mkfs.ext4` and `e2fsck` to bring Tomb to the party (see https://github.com/dyne/Tomb/issues/338).

**Comment by xeffyr** [comment]
Package is now available.

You can obtain it with these commands:
```
pkg install unstable-repo
pkg install e2fsprogs
```

**Comment by xeffyr** [comment]
Oops, this package conflicts with krb5...
