### ISSUE TITLE
Error While Building ZeroNet package

### ISSUE THREAD

**Issue by canewsin** [termux/unstable-packages#158]
OS : Ubuntu 
Docker enviroment in setted up

`./build-package.sh -a arm zeronet`

Error : 
```
ERROR: Package pandoc depends on non-existing package "qemu-user-x86_64"
ERROR: Obtaining buildorder failed

```

**Comment by xeffyr** [comment]
Fixed now.
Requires running `git submodule deinit --all -f` before `./start-builder.sh` to force switch to updated termux-packages submodule.
