### ISSUE TITLE
ruby warnings on metasploit startup

### ISSUE THREAD

**Issue by ilyapashuk** [termux/unstable-packages#172]
: when starting metasploit after last update, get:
 /data/data/com.termux/files/usr/lib/ruby/gems/2.7.0/gems/activerecord-4.2.11.1/l
 ib/active_record/connection_adapters/abstract_adapter.rb:84: warning: deprecated
  Object#=~ is called on Integer; it always returns nil
and some other warnings

also, fixes from:
https://github.com/termux/unstable-packages/commit/f4b60eaef38436e7fb289a52d8f146ea6c4ba057
not in apt package yet or applied not to correct file, not working after installation, I was need to replace version number manually.

**Comment by ilyapashuk** [comment]
debian bundle of metasploit, version 5.81x, uses ruby 2.6.5, our version is older.

**Comment by xeffyr** [comment]
> : when starting metasploit after last update, get:

Ignore warnings.

> not in apt package yet or applied not to correct file

Will be fixed shortly.
