### ISSUE TITLE
Metasploit (5.0.80) don't run 2.6.0

### ISSUE THREAD

**Issue by MiguelEXE** [termux/unstable-packages#173]
Im trying to run metasploit, but it says i need ruby 2.6.0 but in the CANNOT LINK EXECUTABLE think

I cant do anything
But i need install ruby 2.6.0
How i do it?

**Comment by xeffyr** [comment]
> But i need install ruby 2.6.0

This is not possible as we don't support package downgrading (though, package manager still does).
