### ISSUE TITLE
msfvenom command threw some warnings

### ISSUE THREAD

**Issue by remo7777** [termux/unstable-packages#174]
**Problem description**

![Screenshot_2020-03-17-07-35-30-93_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/28594846/76815473-b2bb8800-6823-11ea-9468-0aa8b0d6d375.jpg)

after execute command
`msfvenom -l platforms`
it threw some warnings.

**Expected behavior**

**System information**

```
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
# unstable-repo (sources.list.d/unstable.list)
deb https://dl.bintray.com/xeffyr/unstable-packages unstable main
Updatable packages:
All packages up to date
Android version:
10
Kernel build information:
Linux localhost 4.9.186-perf+ #2 SMP PREEMPT Fri Feb 28 01:48:42 CST 2020 aarch64 Android
Device manufacturer:
realme
Device model:
RMX1921
```

**Comment by remo7777** [comment]
i had not faced older version ruby

**Comment by Grimler91** [comment]
Seems the new ruby version has deprecated some commands and some ruby gems (activerecord, faraday) have not been updated to not use these commands. 

This is not termux-specific, or termux-related so I am closing this
