### ISSUE TITLE
Package request: translate-shell

### ISSUE THREAD

**Issue by shfrs** [termux/unstable-packages#2]
Command-line translator using Google Translate, Bing Translator, Yandex.Translate, etc. Program is written in awk.
Dependencies:
- GNU Awk (gawk) 4.0 or later (already implemented in termux)
- GNU Bash or Zsh 
https://www.soimort.org/translate-shell/
https://github.com/soimort/translate-shell

**Comment by xeffyr** [comment]
Package is now available.

You can obtain it with these commands:
```
pkg install unstable-repo
pkg install translate-shell
```
