### ISSUE TITLE
Package request: links (links2)

### ISSUE THREAD

**Issue by Symbian9** [termux/unstable-packages#25]
Please, add `links` (`links2`) for Termux, as alternative to `elinks` / `lynx` / `w3m`.
-  http://links.twibright.com
  - http://links.twibright.com/download.php
  - http://links.twibright.com/download/ChangeLog
  - http://links.twibright.com/development.php

[![Packaging status](https://repology.org/badge/vertical-allrepos/links.svg)](https://repology.org/metapackage/links)

**Comment by xeffyr** [comment]
Package is now available.

You can obtain it with these commands:
```
pkg install unstable-repo
pkg install links
```
