### ISSUE TITLE
package requests: haproxy

### ISSUE THREAD

**Issue by orencio** [termux/unstable-packages#31]
I should be useful haproxy \[1\]\[2\] in android devices installed and managed by termux.
Sometimes is needed to configure client-side balance services.

One example (useful for me) is alpine-tor \[3\] configuration in Android with tor services.

Regards.

----
\[1\]: HAProxy: <https://www.haproxy.org/>
\[2\]: Debian package for HAProxy: <https://packages.debian.org/search?searchon=names&keywords=haproxy>
\[3\]: alpine-tor: <https://github.com/zet4/alpine-tor>

**Comment by xeffyr** [comment]
Package is now available.

You can obtain it with these commands:
```
pkg install unstable-repo
pkg install haproxy
```

**Comment by sqliuchang** [comment]
> Package is now available.
> 
> You can obtain it with these commands:
> 
> ```
> pkg install unstable-repo
> pkg install haproxy
> ```

I have installed haproxy in unstable-repo and execed it, but it shows
"zsh: exec format error: haproxy'
How to solve this?

**Comment by xeffyr** [comment]
> exec format error: haproxy

Should be fixed now.

**Comment by sqliuchang** [comment]
> Should be fixed now.
It works now. Thank you!
