### ISSUE TITLE
Package request: proxychains-ng

### ISSUE THREAD

**Issue by samos123** [termux/unstable-packages#33]
I often need to SSH through socks5 proxies and proxychains is my favorite for that. Planning to look into building the package myself. I tried to directly compile from termux but that didn't work :P

Upstream repo: https://github.com/rofl0r/proxychains-ng

**Comment by xeffyr** [comment]
Package is now available.

You can obtain it with these commands:
```
pkg install unstable-repo
pkg install proxychains-ng
```
