### ISSUE TITLE
Package request: sc-im

### ISSUE THREAD

**Issue by buribu** [termux/unstable-packages#34]
SC-IM is a spreadsheet program that is based on SC
Some of the features of SC-IM
UNDO / REDO.
65.536 rows and 702 columns supported. (The number of rows can be expanded to 1.048.576 if wished).
CSV / TAB delimited file import and export.
XLS / XLSX file import.
Key-mappings.
Sort of rows...
https://github.com/andmarti1424/sc-im

**Comment by xeffyr** [comment]
Package is now available.

You can obtain it with these commands:
```
pkg install unstable-repo
pkg install sc-im
```
