### ISSUE TITLE
Package request: lesspipe

### ISSUE THREAD

**Issue by c-e-p-x-u-o** [termux/unstable-packages#4]
Please add lesspipe, a preprocessor for less.

https://sourceforge.net/projects/lesspipe/
https://github.com/wofr06/lesspipe

**Comment by xeffyr** [comment]
Package is now available.

You can obtain it with these commands:
```
pkg install unstable-repo
pkg install lesspipe
```

**Comment by c-e-p-x-u-o** [comment]
Thank you!

Is there a way to browse unstable-repo?

**Comment by xeffyr** [comment]
To view list of packages in unstable-repo, do this:
```
apt list | grep /unstable
```

**Comment by c-e-p-x-u-o** [comment]
Just fyi: in debian lesspipe is included into less package. May be it will be better to do the same.
