### ISSUE TITLE
Package Request: Git LFS

### ISSUE THREAD

**Issue by thurask** [termux/unstable-packages#48]
https://github.com/github/git-lfs?utm_source=gitlfs_site&utm_medium=source_link&utm_campaign=gitlfs

I tried to build it on-device (with go get), but ran into a problem with /usr/bin/env and "bad interpreter" or something like that.

**Comment by xeffyr** [comment]
Package is now available.

You can obtain it with these commands:
```
pkg install unstable-repo
pkg install git-lfs
```
