### ISSUE TITLE
request: geckodriver

### ISSUE THREAD

**Issue by myfreess** [termux/unstable-packages#56]
its writen by rust,and build script its only for crosscompile.
it is also require libgcc,but libgcc not found on offical repo……
want a way to compile it    :D

**Comment by xeffyr** [comment]
Package is now available.

You can obtain it with these commands:
```
pkg install unstable-repo
pkg install geckodriver
```

**Comment by darknodi** [comment]
@xeffyr yntaxError: invalid syntax
                                           [!] Heuristics indicate your version of PyCurl does not support OpenSSL

**Comment by Gidraf** [comment]
@xeffyr I am unable to download the package. This is the error I am getting.
![Screenshot_20200218-070922](https://user-images.githubusercontent.com/30722290/74703305-0b8c0680-520d-11ea-8d93-bc8ef77881a3.png)

**Comment by xeffyr** [comment]
@Gidraf `geckodriver` package is removed due to no use cases inside Termux - we don't have `firefox` packaged and Geckodriver does not work with mobile Firefox application.
