### ISSUE TITLE
Nikto Has Been Ported ! Take A Look at The Deb Package

### ISSUE THREAD

**Issue by RootSh311** [termux/unstable-packages#64]
nikto has been ported here is link of nikto.deb
https://www.mediafire.com/file/vmeqdcj6h98b477/nikto_2.1.6_all.deb/file
Take A Look
![screenshot_20190227-233151](https://user-images.githubusercontent.com/47913604/53510520-6900e200-3ae8-11e9-8b23-08260594c89f.png)

**Comment by xeffyr** [comment]
> WARNING: SSL: support not available

No ssl because of no perl modules.
Just package nikto archive and say "it's ported", that's.... LOL
