### ISSUE TITLE
Package Request: tidy (libtidy)

### ISSUE THREAD

**Issue by gnirlos** [termux/unstable-packages#7]
I followed the directions on [tidy on github](https://github.com/htacg/tidy-html5/blob/next/README/BUILD.md) and was able to build tidy within termux...but only after dealing with the issue of undefined type for ulong.

The type is defined in this codeblock within tidyplatform.h:

```
#if defined(HPUX_OS) || defined(CYGWIN_OS) || defined(MAC_OS) || defined(BSD_BASED_OS) || defined(_WIN32)
# undef ulong
    typedef unsigned long ulong;
#endif

```
Since none of those #defines apply for termux on android, ulong doesn't get set.  I pulled the typdef out of the #if-#endif clause and was able to successful compile and tidy appears to be working fine.

Is this kind of this usual practice when porting existing apps onto termux?  Is this a bug I should report?  ...not sure what to do here...

**Comment by xeffyr** [comment]
Package is now available.

You can obtain it with these commands:
```
pkg install unstable-repo
pkg install tidy
```
