### ISSUE TITLE
CANNOT LINK EXECUTABLE: library "PREFIX=/data/data/com.termux/files/usr" not found

### ISSUE THREAD

**Issue by shownb** [termux/unstable-packages#73]
i installed Metasploit like that
https://wiki.termux.com/wiki/Metasploit_Framework

when i run
msfconsole

it show that:
CANNOT LINK EXECUTABLE: library "PREFIX=/data/data/com.termux/files/usr" not found
page record for 0xb6f0101c was not found (block_size=16)

can someone help?

**Comment by xeffyr** [comment]
Seems to be fixed with [update](https://github.com/termux/unstable-packages/commit/512ffdfacb5e258e98116dd7da0ee68db3dae84f).

**Comment by alshosh** [comment]
I have same issus
