### ISSUE TITLE
Metasploit Auxiliary failed

### ISSUE THREAD

**Issue by dipayand** [termux/unstable-packages#79]
msf5 > use auxiliary/gather/enum_dns
msf5 auxiliary(gather/enum_dns) > set DOMAIN yahoo.com
DOMAIN => yahoo.com
msf5 auxiliary(gather/enum_dns) > run

[-] Auxiliary failed: Errno::ENOENT No such file or directory @ rb_sysopen - /etc/resolv.conf
[-] Call stack:
[-]   /data/data/com.termux/files/usr/opt/metasploit-framework/lib/net/dns/resolver.rb:1086:in `foreach'
[-]   /data/data/com.termux/files/usr/opt/metasploit-framework/lib/net/dns/resolver.rb:1086:in `parse_config_file'
[-]   /data/data/com.termux/files/usr/opt/metasploit-framework/lib/net/dns/resolver.rb:230:in `initialize'
[-]   /data/data/com.termux/files/usr/opt/metasploit-framework/modules/auxiliary/gather/enum_dns.rb:87:in `new'
[-]   /data/data/com.termux/files/usr/opt/metasploit-framework/modules/auxiliary/gather/enum_dns.rb:87:in `dns_query'
[-]   /data/data/com.termux/files/usr/opt/metasploit-framework/modules/auxiliary/gather/enum_dns.rb:203:in `get_a'
[-]   /data/data/com.termux/files/usr/opt/metasploit-framework/modules/auxiliary/gather/enum_dns.rb:178:in `dns_wildcard_enabled?'
[-]   /data/data/com.termux/files/usr/opt/metasploit-framework/modules/auxiliary/gather/enum_dns.rb:61:in `run'
[*] Auxiliary module execution completed
msf5 auxiliary(gather/enum_dns) >

**Comment by xeffyr** [comment]
Should be fixed in version `5.0.13-2`.
