### ISSUE TITLE
SET(toolkit) can't find Metasploit

### ISSUE THREAD

**Issue by PropsFura** [termux/unstable-packages#84]
I have installed Metasploit already. Then installed SET and when i open it,everything is ok but when i use any social attack it feedback to me : Can't find Metasploit

**Comment by xeffyr** [comment]
setoolkit has a lot of hardcoded paths and because of that it doesn't know where metasploit is installed. Setoolkit is not portable as well as it won't be able to handle Termux-specific [metasploit ruby fix](https://github.com/termux/unstable-packages/blob/master/packages/metasploit/msfconsole.sh).
