### ISSUE TITLE
Linking yasm compiled program in termux using ld

### ISSUE THREAD

**Issue by lucasalferdo** [termux/unstable-packages#89]
I'm trying to link programs compiled by yasm in termux with x86_64 ld binary and I almost succeed but I can't execute the binary.

# How to reproduce ?
> wget https://0x0.st/zAWz.zip -O y32.zip
> unzip y32.zip && cd y32
> ./runtest 

# Output:
> /use/lib/libc.so.1 not found

BTW, libc.so.1 is just symlink of libc.so. so, let's try.
> ln -sf libc.so libc.so.1
> sed -i 's,/use/lib/libc.so.1,libc.so.1,g' neg
> qemu-i386 ./neg

# Output:
It says it's for different architecture
 
What's the problem actually ?

@xeffyr

**Comment by xeffyr** [comment]
```
yasm -felf neg.asm
qemu-x86_64 ./ld -melf_i386 neg.o -o neg -lc -L ${PWD}
patchelf --set-interpreter ./ld-linux.so.2 ./neg
patchelf --set-rpath ./ ./neg
qemu-i386 ./neg
```

**Comment by lucasalferdo** [comment]
Thanks man you're awesome

**Comment by lucasalferdo** [comment]
> ```
> yasm -felf neg.asm
> qemu-x86_64 ./ld -melf_i386 neg.o -o neg -lc -L ${PWD}
> patchelf --set-interpreter ./ld-linux.so.2 ./neg
> patchelf --set-rpath ./ ./neg
> qemu-i386 ./neg
> ```

@xeffyr it shows core dumped

**Comment by xeffyr** [comment]
It doesn't work on real x86 Linux machine.

**Comment by lucasalferdo** [comment]
> It doesn't work on real x86 Linux machine.
> Problem is in the source code.

Maybe have to use prebuild yasm binary for x86 and use it with qemu ?

**Comment by lucasalferdo** [comment]
You can try compile any file from here in termux
https://github.com/xorpd/asm_prog_ex_yasm

**Comment by xeffyr** [comment]
Because GCC adds some C library initialization stuff.

**Comment by xeffyr** [comment]
```
/lib/gcc/i686-pc-linux-gnu/8.2.1/crtbegin.o
/lib/gcc/i686-pc-linux-gnu/8.2.1/crtbeginS.o
/lib/gcc/i686-pc-linux-gnu/8.2.1/crtbeginT.o
/lib/gcc/i686-pc-linux-gnu/8.2.1/crtend.o
/lib/gcc/i686-pc-linux-gnu/8.2.1/crtendS.o
/lib/gcc/i686-pc-linux-gnu/8.2.1/crtfastmath.o
/lib/gcc/i686-pc-linux-gnu/8.2.1/crtprec32.o
/lib/gcc/i686-pc-linux-gnu/8.2.1/crtprec64.o
/lib/gcc/i686-pc-linux-gnu/8.2.1/crtprec80.o
```

**Comment by lucasalferdo** [comment]
> ```
> /lib/gcc/i686-pc-linux-gnu/8.2.1/crtbegin.o
> /lib/gcc/i686-pc-linux-gnu/8.2.1/crtbeginS.o
> /lib/gcc/i686-pc-linux-gnu/8.2.1/crtbeginT.o
> /lib/gcc/i686-pc-linux-gnu/8.2.1/crtend.o
> /lib/gcc/i686-pc-linux-gnu/8.2.1/crtendS.o
> /lib/gcc/i686-pc-linux-gnu/8.2.1/crtfastmath.o
> /lib/gcc/i686-pc-linux-gnu/8.2.1/crtprec32.o
> /lib/gcc/i686-pc-linux-gnu/8.2.1/crtprec64.o
> /lib/gcc/i686-pc-linux-gnu/8.2.1/crtprec80.o
> ```
> 
> ```
> /usr/lib/gcc/i686-pc-linux-gnu/8.2.1/collect2 -plugin /usr/lib/gcc/i686-pc-linux-gnu/8.2.1/liblto_plugin.so -plugin-opt=/usr/lib/gcc/i686-pc-linux-gnu/8.2.1/lto-wrapper -plugin-opt=-fresolution=/tmp/ccQtDtUx.res -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lc -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s --build-id --eh-frame-hdr --hash-style=gnu -m elf_i386 -dynamic-linker /lib/ld-linux.so.2 -pie -o neg /usr/lib/gcc/i686-pc-linux-gnu/8.2.1/../../../Scrt1.o /usr/lib/gcc/i686-pc-linux-gnu/8.2.1/../../../crti.o /usr/lib/gcc/i686-pc-linux-gnu/8.2.1/crtbeginS.o -L/usr/lib/gcc/i686-pc-linux-gnu/8.2.1 -L/usr/lib/gcc/i686-pc-linux-gnu/8.2.1/../../.. neg.o -lgcc --as-needed -lgcc_s --no-as-needed -lc -lgcc --as-needed -lgcc_s --no-as-needed /usr/lib/gcc/i686-pc-linux-gnu/8.2.1/crtendS.o /usr/lib/gcc/i686-pc-linux-gnu/8.2.1/../../../crtn.o
> ```

what I need to do now?
Is it possible to do this with some how gcc in termux ?
If we take x86 (32bit) gcc ?

**Comment by lucasalferdo** [comment]
Is it possible to install x86 32bit gcc in termux and then use qemu to emulate it to get it working somehow ?

**Comment by xeffyr** [comment]
Possible. With proot + qemu-user-i386 + x86 ubuntu rootfs.

**Comment by lucasalferdo** [comment]
> Possible. With proot + qemu-user-i386 + x86 ubuntu rootfs.

Is there any documentation to get x86 Ubuntu rootfs ? And emulate it with qemu-user-i386 ?
If possible 32bit Ubuntu 18.10 or Ubuntu 19.10 (ermine) ?

**Comment by lucasalferdo** [comment]
Moreover, can you tell me steps to achieve this goal ?
> proot + qemu-user-i386 + x86 ubuntu rootfs.

And can I use your Alpine term and select this image and boot it ?
