### ISSUE TITLE
Ubuntu x86_64 rootfs + qemu x86_64 + proot

### ISSUE THREAD

**Issue by lucasalferdo** [termux/unstable-packages#90]
Need a proper way to do this.
As i don't have much experience in this.
@xeffyr you told i can run ubuntu 18 or 19 with your alpine term. How can i ?
I know i have to choose location to image but what image to exactly choose ?
Link me to it please

**Comment by xeffyr** [comment]
> How can i ?

Chroot not working ?

> what image to exactly choose ?

In case of chroot, you need rootfs archive and not image.
https://partner-images.canonical.com/core/bionic/current/ubuntu-bionic-core-cloudimg-amd64-root.tar.gz

**Comment by lucasalferdo** [comment]
> > How can i ?
> 
> Chroot not working ?
> 
> > what image to exactly choose ?
> 
> In case of chroot, you need rootfs archive and not image.
> 64 bit: https://partner-images.canonical.com/core/bionic/current/ubuntu-bionic-core-cloudimg-amd64-root.tar.gz
> 
> 32 bit: https://partner-images.canonical.com/core/bionic/current/ubuntu-bionic-core-cloudimg-i386-root.tar.gz

I want to run this in your Alpine term how can I ?
Should I just supply path to one of these tarballs ?

**Comment by xeffyr** [comment]
Tarballs should be extracted to dir and executed with `chroot`.

Image is https://cloud-images.ubuntu.com/disco/current/disco-server-cloudimg-amd64.img, but Ubuntu images are not working here without manual intervention into boot process.

**Comment by lucasalferdo** [comment]
> Tarballs should be extracted to dir and executed with `chroot`.
> 
> Image is https://cloud-images.ubuntu.com/disco/current/disco-server-cloudimg-amd64.img, but Ubuntu images are not working here without manual intervention into boot process (will drop into initramfs shell).

So I can't run it in Alpine term :(

**Comment by lucasalferdo** [comment]
@xeffyr 

Can you update this for qemu one ?
https://github.com/Neo-Oli/termux-ubuntu/blob/master/ubuntu.sh
