### ISSUE TITLE
Package Request:Elixir

### ISSUE THREAD

**Issue by myfreess** [termux/unstable-packages#91]
Its a dynamic functional programming language，wrote by Erlang。

~I try to compile it in Termux，but failed…… ~

precomplied binary on here:[elixir](https://github.com/elixir-lang/elixir/releases/)，just relie on erlang。it works well。

**Comment by xeffyr** [comment]
Package is now available.

You can obtain it with these commands:
```
pkg install unstable-repo
pkg install elixir
```
