### ISSUE TITLE
Package request: Roc

### ISSUE THREAD

**Issue by S-trace** [termux/unstable-packages#93]
Hello.

I'm rying to build roc (https://roc-project.github.io/) with PulseAudio module to steam hi-quality audio from PC to Android (to use Android phone as WiFi headset), but build fails during configure.

Could You please help me with porting roc to the Android/Termux?
Build scripts for Termux packages (scons, libopenfec and roc): [packages.zip](https://github.com/termux/unstable-packages/files/3290525/packages.zip)

Thank You.

**Comment by xeffyr** [comment]
Package `roc` is now available. Install it with `pkg install roc`.

**Comment by gavv** [comment]
FYI: @S-trace have also opened [an issue](https://github.com/roc-project/roc/issues/222) in Roc and it seems that I've fixed all (or almost all) issues covered with the SConstruct.patch. I didn't know that you're working on this too. Those changes are in the develop branch and there is not tagged release so far. PulseAudio modules are not working yet.
