### ISSUE TITLE
unable to install metasploit  framework

### ISSUE THREAD

**Issue by tiwari9662** [termux/unstable-packages#95]
Unable to install metasploit in termux it shows xyz code ------ Get:9 https://dl.bintray.com/grimler/science-packages-24 science Release [5348 B]
Hit:9 https://dl.bintray.com/grimler/science-packages-24 science Release
Get:11 https://dl.bintray.com/xeffyr/unstable-packages-24 unstable Release [6065 B]
Hit:11 https://dl.bintray.com/xeffyr/unstable-packages-24 unstable Release
Reading package lists... Done
Building dependency tree
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package metasploit-framework
$

**Comment by Grimler91** [comment]
It's named `metasploit`, not `metasploit-framework` [in this repo](https://github.com/termux/unstable-packages/tree/master/packages/metasploit).

**Comment by ZVin-Chen** [comment]
you could install by type code below directly 

pkg install unstable-repo
pkg install metasploit
