### ISSUE TITLE
Mupdf

### ISSUE THREAD

**Issue by igavronski** [termux/unstable-packages#96]
**Package description**

We need this package to manipulate PDF files with Python (pip install pymupdf)

**Link to home page and sources**
1. Home page: 
2. Source code: https://mupdf.com/docs/building.html

**Additional information**
Have you compiled or tried to compile the package on device?
* If it didn't work then please provide the error you ran into
* If it did work then please share any patches that you had to apply

**Comment by xeffyr** [comment]
Package is now available.

You can obtain it with these commands:
```
pkg install unstable-repo
pkg install mupdf
```

> I had to manually link (ln -s) the file in the include directory because it was installed on include/mupdf instead of the include directory.

You don't need to symlink. Just add `-I$PREFIX/include/mupdf` to CFLAGS environment variable.

**Comment by igavronski** [comment]
In fact, my ultimate goal was not achieved.
I want to run 
pip3 install pymupdf
python
import fitz

The mupdf version required is 1.14, not the 1.15 in the repo.

Thanks anyway ,

Iuri.
