### ISSUE TITLE
[PACKAGE SUBMISSION] SIXEL

### ISSUE THREAD

**Issue by talentlessguy** [termux/unstable-packages#97]
This package provides encoder/decoder implementation for DEC SIXEL graphics, and some converter programs.

SIXEL is one of image formats for printer and terminal imaging. Its data scheme is represented as a terminal-friendly escape sequence. So if you want to view a SIXEL image file.

GitHub repository: https://github.com/saitoha/libsixel

Python library:
https://pypi.org/project/libsixel-python/0.4.0/

and also Perl6, if needed: https://github.com/timo/libsixel-p6

**Comment by xeffyr** [comment]
Package is now available.

You can obtain it with these commands:
```
pkg install unstable-repo
pkg install libsixel
```
