### ISSUE TITLE
[Package Request] nmh

### ISSUE THREAD

**Issue by geometryof** [termux/unstable-packages#98]
**Package description**
Quite simply the best command-line mail client.  Integrates beautifully with emacs.

**Link to home page and sources**
1. Home page: https://www.nongnu.org/nmh/
2. Source code: https://download.savannah.nongnu.org/releases/nmh/

**Comment by xeffyr** [comment]
Package is now available.

You can obtain it with these commands:
```
pkg install unstable-repo
pkg install nmh
```

Note: if you still use an Android-5 repository (termux.net), there is possibility of linking errors due to some missing stuff in package `gdbm`. Will be fixed after merging https://github.com/termux/termux-packages/pull/3995.
