### ISSUE TITLE
Package request: steghide

### ISSUE THREAD

**Issue by HoangPhantom** [termux/unstable-packages#99]
This is a cryptographic tool that is used to hide data in image, audio files and more:

Homepage:
http://steghide.sourceforge.net/

Source:
https://github.com/StefanoDeVuono/steghide

I haven't tried it myself. Because I fear that it will take too much storage.

**Comment by xeffyr** [comment]
Package is now available.

You can obtain it with these commands:
```
pkg install unstable-repo
pkg install steghide
```

**Comment by Arslan186** [comment]
The repository 'https://dl.bintray.com/termux/termux-packages-24 stable Release' does no longer have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by Arslan186** [comment]
The repository 'https://dl.bintray.com/termux/termux-packages-24 stable Release' does no longer have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.The repository 'https://dl.bintray.com/termux/termux-packages-24 stable Release' does no longer have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by Grimler91** [comment]
@Arslan186 See https://github.com/termux/termux-packages/issues/4358
